import { VStack, Text, Spinner } from "@chakra-ui/react";
import { motion } from "framer-motion";
import { useAppContext } from "../contexts/AppStateContext";

/**
 * UI is displayed when some aspect of the story
 * is being generated by the machine learning model
 */
const GeneratingLoadingUI = () => {
  const { generatingFinished, generating, whichAct } = useAppContext();

  const loadingLabel: Record<number, string> = {
    1: "the introduction of your story",
    2: "the first act of your story",
    3: "the second act of your story",
    4: "the final act of your story",
  };

  return (
    <motion.div
      style={{
        opacity: 0,
        display: generating ? "flex" : "none",
      }}
      animate={{
        opacity: generatingFinished ? [1, 0] : generating ? [0, 1] : [1, 0],
      }}
      transition={{
        ease: "easeInOut",
        duration: 1,
        delay: 0,
      }}
    >
      <VStack h="100%" pt="25%" spacing="10" w="100%">
        <Text fontFamily="YsabeauInfant" color="white" fontSize="28px">
          Generating {loadingLabel[whichAct]}
        </Text>
        <Spinner color="white" size="xl" />
      </VStack>
    </motion.div>
  );
};

export default GeneratingLoadingUI;
