import { VStack, Text } from "@chakra-ui/react";
import { motion } from "framer-motion";
import { useAppContext } from "../contexts/AppStateContext";
import StaticAppButton from "./StaticAppButton";

/**
 * UI is displayed when some aspect of the story
 * is being generated by the machine learning model
 */
const GeneratingErrorUI = () => {
  const { generatingError, restartGame, generating } = useAppContext();

  return (
    <motion.div
      style={{
        opacity: 0,
        display: generatingError && !generating ? "flex" : "none",
      }}
      animate={{
        opacity: [0, 1],
      }}
      transition={{
        ease: "easeInOut",
        duration: 1,
        delay: 1,
      }}
    >
      <VStack h="100%" pt="25%" spacing="10" w="100%">
        <Text fontFamily="YsabeauInfant" color="white" fontSize="28px">
          There was an unexpected error
        </Text>
        <Text
          fontFamily="YsabeauInfant"
          color="white"
          fontSize="20px"
          w="80%"
          textAlign="center"
        >
          Apologies, there appears to be an error when generating your story.
          Please check your OpenAI API key, and try again later.
        </Text>
        <StaticAppButton
          height={60}
          width={240}
          fontSize={20}
          action={restartGame}
          label="Return to Main Menu"
        />
      </VStack>
    </motion.div>
  );
};

export default GeneratingErrorUI;
