import { VStack, Text, Spinner } from "@chakra-ui/react";
import { motion } from "framer-motion";
import { useAppContext } from "../contexts/AppStateContext";

interface IGeneratingLoadingUI {
  label: string;
}

/**
 * UI is displayed when some aspect of the story
 * is being generated by the machine learning model
 */
const GeneratingLoadingUI = ({ label }: IGeneratingLoadingUI) => {
  const { generatingFinished, generating } = useAppContext();

  return (
    <motion.div
      style={{
        opacity: 0,
        display: generating ? "flex" : "none",
      }}
      animate={{
        opacity: generatingFinished ? [1, 0] : generating ? [0, 1] : [1, 0],
      }}
      transition={{
        ease: "easeInOut",
        duration: 1,
        delay: 0,
      }}
    >
      <VStack h="100%" pt="25%" spacing="10" w="100%">
        <Text fontFamily="YsabeauInfant" color="white" fontSize="28px">
          Generating {label}
        </Text>
        <Spinner color="white" size="xl" />
      </VStack>
    </motion.div>
  );
};

export default GeneratingLoadingUI;
