import { VStack, Text, Spinner } from "@chakra-ui/react";
import { motion } from "framer-motion";
import { useAppContext } from "../contexts/AppStateContext";

interface IGeneratingLoadingUI {
  label: string;
  screenTransitionDuration: number;
}

/**
 * UI is displayed when some aspect of the story
 * is being generated by the machine learning model
 */
const GeneratingLoadingUI = ({
  label,
  screenTransitionDuration,
}: IGeneratingLoadingUI) => {
  const { generatingFinished } = useAppContext();

  return (
    <motion.div
      style={{
        opacity: 0,
      }}
      animate={{
        opacity: generatingFinished ? [1, 0] : [0, 1],
      }}
      transition={{
        ease: "easeInOut",
        duration: screenTransitionDuration,
        delay: 0,
      }}
    >
      <VStack h="100%" pt="20%" spacing="10">
        <Text fontFamily="YsabeauInfant" color="white" fontSize="28px">
          Generating {label}
        </Text>
        <Spinner color="white" size="xl" />
      </VStack>
    </motion.div>
  );
};

export default GeneratingLoadingUI;
